version: '3.9'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - ${MONGODB_DOCKER_PORT}:${MONGODB_DOCKER_PORT}
    volumes:
      - node-mongo-data
  node:
    depends_on:
      - mongodb
    build: .
    command: npm run dev
    restart: unless-stopped
    env_file: .env
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    environment:
      - NODE_PORT=${NODE_PORT}
      - DB_HOST=mongodb
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_NAME=${MONGODB_DATABASE}
      - DB_PORT=${MONGODB_DOCKER_PORT}
    volumes:
      - ./:/usr/src/app
      - ignore:/usr/src/app/node_modules/
volumes:
  node-mongo-data:
  ignore: