version: '3'

services:
  app:
    container_name: backend-ais
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    working_dir: /code
    env_file: 
     - .env.development
    depends_on:
      - postgres
    ports:
      - "${NODE_PORT}:3000"
    volumes:
      - ./:/code
  postgres:
    container_name: database-postgres-ais
    image: postgres:11
    env_file: 
     - .env.development
    ports:
      - "${DATABASE_POSTGRE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_POSTGRE_USER}
      POSTGRES_PASSWORD: ${DATABASE_POSTGRE_PASS}
      POSTGRES_DB: ${DATABASE_POSTGRE_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data