
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Make directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST}}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          rm -r /var/www/interactive
          mkdir /var/www/interactive

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/var/www/interactive"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/interactive
          sudo chown -R $USER /var/www/interactive
          cat <<EOF > .env
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          HOST_URL=${{ secrets.HOST_URL }}
          API_URL=${{ secrets.API_URL }}
          API_TOKEN=${{ secrets.API_TOKEN }}
          EOF
          chmod +x deploy.sh
          sh deploy.sh